## Theme
theme: minimal-mistakes-jekyll

## Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      show_date: true

## General
title      : "Luis Gustavo Nardin"
description: ""
url        : "https://gnardin.github.io"
baseurl    : ""
locale     : "en_US"
breadcrumbs: true
atom_feed:
  hide: true

## Author
author:
  avatar   : "/assets/images/profile-photo.jpg"
  bio      : ""
  location : "Saint-Étienne, France"
  links:
    - label: "Email"
      icon : "far fa-fw fa-envelope"
      url  : "mailto:gnardin@emse.fr"
    - label: "Website"
      icon : "fas fa-fw fa-link"
      url  : "https://gnardin.github.io/website"
    - label: "GitHub"
      icon : "fab fa-fw fa-github"
      url  : "https://github.com/gnardin/"
    - label: "GitLab"
      icon : "fa fa-gitlab"
      url  : "https://gitlab.emse.fr/gnardin/"
    - label: "Google Scholar"
      icon : "fas fa-fw fa-graduation-cap"
      url  : "https://scholar.google.com/citations?hl=fr&user=bHSraDkAAAAJ"
    - label: "LinkedIn"
      icon : "fab fa-fw fa-linkedin"
      url  : "https://www.linkedin.com/in/luis-gustavo-nardin-92091814/"
    - label: "ORCID"
      icon : "fab fa-fw fa-orcid"
      url  : "https://orcid.org/0000-0002-4506-2745"
      
include: ["_pages"]
